In [5]:
conda install -y -c conda-forge geopandas pyogrio shapely rtree pyproj fiona pyarrow

Retrieving notices: done
Channels:
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 24.11.3
    latest version: 25.9.1

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/.conda

  added / updated specs:
    - fiona
    - geopandas
    - pyarrow
    - pyogrio
    - pyproj
    - rtree
    - shapely


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aws-c-auth-0.9.1           |       h8818502_7         104 KB  conda-forge
    aws-c-cal-0.9.10           |       hca30140_1          44 KB  conda-forge
    aws-c-common-0.12.5        |       hc919400_1         218 KB  conda-forge
    aws-c-compression-0.3.1    |       h61d5560_8          21 KB  conda-forge
    aws-c-event-stream-0.5.6   |       h18584fc_6          51 KB  conda-forge
    aws-c-http-0.10.7          |       hcd69b29_4         167 KB  conda-forge
    aws-c-io-0.23.3            |       h9710c81_3         172 KB  conda-forge
    aws-c-mqtt-0.13.3          |      ha255ef3_10         147 KB  conda-forge
    aws-c-s3-0.10.1            |       hd860258_2         125 KB  conda-forge
    aws-c-sdkutils-0.2.4       |       h61d5560_3          52 KB  conda-forge
    aws-checksums-0.2.7        |       h61d5560_4          72 KB  conda-forge
    aws-crt-cpp-0.35.2         |       h5596a46_4         260 KB  conda-forge
    aws-sdk-cpp-1.11.606       |       h95becb6_7         3.0 MB  conda-forge
    branca-0.8.2               |     pyhd8ed1ab_0          29 KB  conda-forge
    brotli-1.2.0               |       hca488c2_0          20 KB  conda-forge
    brotli-bin-1.2.0           |       hce9b42c_0          18 KB  conda-forge
    brotli-python-1.2.0        |  py311h69b7e7c_0         351 KB  conda-forge
    ca-certificates-2025.11.12 |       hbd8a1cb_0         149 KB  conda-forge
    certifi-2025.11.12         |     pyhd8ed1ab_0         153 KB  conda-forge
    cffi-2.0.0                 |  py311hd10dc20_1         288 KB  conda-forge
    click-8.3.1                |     pyh707e725_0          90 KB  conda-forge
    contourpy-1.3.3            |  py311h5a5e7c7_3         253 KB  conda-forge
    fonttools-4.60.1           |  py311ha9b3269_0         2.8 MB  conda-forge
    geopandas-1.1.1            |     pyhd8ed1ab_1           8 KB  conda-forge
    geopandas-base-1.1.1       |     pyha770c72_1         245 KB  conda-forge
    geos-3.14.1                |       h5afe852_0         1.5 MB  conda-forge
    geotiff-1.7.4              |       hf862be1_4         125 KB  conda-forge
    kiwisolver-1.4.9           |  py311h26d6576_2          65 KB  conda-forge
    libarrow-22.0.0            |   h4a3aeba_4_cpu         4.0 MB  conda-forge
    libarrow-acero-22.0.0      |   hc317990_4_cpu         506 KB  conda-forge
    libarrow-compute-22.0.0    |   h75845d1_4_cpu         2.1 MB  conda-forge
    libarrow-dataset-22.0.0    |   hc317990_4_cpu         503 KB  conda-forge
    libarrow-substrait-22.0.0  |   h144af7f_4_cpu         442 KB  conda-forge
    libblas-3.11.0             |2_h51639a9_openblas          18 KB  conda-forge
    libbrotlicommon-1.2.0      |       h87ba0bc_0          77 KB  conda-forge
    libbrotlidec-1.2.0         |       h95a88de_0          29 KB  conda-forge
    libbrotlienc-1.2.0         |       hb1b9735_0         284 KB  conda-forge
    libcblas-3.11.0            |2_hb0561ab_openblas          18 KB  conda-forge
    libcurl-8.17.0             |       hdece5d2_0         385 KB  conda-forge
    libcxx-21.1.6              |       hf598326_0         556 KB  conda-forge
    libdeflate-1.25            |       hc11a715_0          54 KB  conda-forge
    libgdal-core-3.10.3        |      h2be85fc_26         8.1 MB  conda-forge
    libjpeg-turbo-3.1.2        |       hc919400_0         538 KB  conda-forge
    liblapack-3.11.0           |2_hd9741b5_openblas          18 KB  conda-forge
    libparquet-22.0.0          |   h0ac143b_4_cpu        1019 KB  conda-forge
    libpng-1.6.51              |       hfab5511_0         281 KB  conda-forge
    libre2-11-2025.11.05       |       h91c62da_0         162 KB  conda-forge
    librttopo-1.1.0            |      ha909e78_20         188 KB  conda-forge
    libspatialite-5.1.0        | gpl_ha239c29_119         2.6 MB  conda-forge
    libtiff-4.7.1              |       h4030677_1         365 KB  conda-forge
    libutf8proc-2.11.1         |       hd2415e0_0          86 KB  conda-forge
    llvm-openmp-21.1.6         |       h4a912ad_0         279 KB  conda-forge
    markupsafe-3.0.3           |  py311ha9b3269_0          26 KB  conda-forge
    matplotlib-base-3.10.8     |  py311h29553df_0         7.9 MB  conda-forge
    networkx-3.6               |     pyhcf101f3_0         1.5 MB  conda-forge
    numpy-2.3.5                |  py311h8685306_0         7.0 MB  conda-forge
    openssl-3.6.0              |       h5503f6c_0         3.0 MB  conda-forge
    pandas-2.3.3               |  py311hdb8e4fa_1        13.7 MB  conda-forge
    pillow-12.0.0              |  py311h890502c_0         944 KB  conda-forge
    proj-9.7.0                 |       hf83150c_0         2.7 MB  conda-forge
    pyarrow-22.0.0             |  py311ha1ab1f8_0          26 KB  conda-forge
    pyarrow-core-22.0.0        |py311hf3e52b4_0_cpu         4.1 MB  conda-forge
    pyproj-3.7.2               |  py311h55f0a08_2         468 KB  conda-forge
    re2-2025.11.05             |       h64b956e_0          27 KB  conda-forge
    scipy-1.16.3               |  py311h2734c94_1        13.4 MB  conda-forge
    shapely-2.1.2              |  py311hd4fb369_2         597 KB  conda-forge
    snappy-1.2.2               |       hada39a4_1          38 KB  conda-forge
    unicodedata2-17.0.0        |  py311h9408147_1         407 KB  conda-forge
    xerces-c-3.3.0             |       hd62221f_0         1.2 MB  conda-forge
    xorg-libxau-1.0.12         |       hc919400_1          14 KB  conda-forge
    xorg-libxdmcp-1.1.5        |       hc919400_1          19 KB  conda-forge
    xyzservices-2025.11.0      |     pyhd8ed1ab_0          50 KB  conda-forge
    zstandard-0.25.0           |  py311h5bb9006_1         381 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        90.2 MB

The following NEW packages will be INSTALLED:

  attrs              conda-forge/noarch::attrs-25.4.0-pyh71513ae_0
  aws-c-auth         conda-forge/osx-arm64::aws-c-auth-0.9.1-h8818502_7
  aws-c-cal          conda-forge/osx-arm64::aws-c-cal-0.9.10-hca30140_1
  aws-c-common       conda-forge/osx-arm64::aws-c-common-0.12.5-hc919400_1
  aws-c-compression  conda-forge/osx-arm64::aws-c-compression-0.3.1-h61d5560_8
  aws-c-event-stream conda-forge/osx-arm64::aws-c-event-stream-0.5.6-h18584fc_6
  aws-c-http         conda-forge/osx-arm64::aws-c-http-0.10.7-hcd69b29_4
  aws-c-io           conda-forge/osx-arm64::aws-c-io-0.23.3-h9710c81_3
  aws-c-mqtt         conda-forge/osx-arm64::aws-c-mqtt-0.13.3-ha255ef3_10
  aws-c-s3           conda-forge/osx-arm64::aws-c-s3-0.10.1-hd860258_2
  aws-c-sdkutils     conda-forge/osx-arm64::aws-c-sdkutils-0.2.4-h61d5560_3
  aws-checksums      conda-forge/osx-arm64::aws-checksums-0.2.7-h61d5560_4
  aws-crt-cpp        conda-forge/osx-arm64::aws-crt-cpp-0.35.2-h5596a46_4
  aws-sdk-cpp        conda-forge/osx-arm64::aws-sdk-cpp-1.11.606-h95becb6_7
  azure-core-cpp     conda-forge/osx-arm64::azure-core-cpp-1.16.1-h88fedcc_0
  azure-identity-cpp conda-forge/osx-arm64::azure-identity-cpp-1.13.2-h853621b_1
  azure-storage-blo~ conda-forge/osx-arm64::azure-storage-blobs-cpp-12.15.0-h10d327b_1
  azure-storage-com~ conda-forge/osx-arm64::azure-storage-common-cpp-12.11.0-h7e4aa5d_1
  azure-storage-fil~ conda-forge/osx-arm64::azure-storage-files-datalake-cpp-12.13.0-hb288d13_1
  blosc              conda-forge/osx-arm64::blosc-1.21.6-h7dd00d9_1
  branca             conda-forge/noarch::branca-0.8.2-pyhd8ed1ab_0
  brotli             conda-forge/osx-arm64::brotli-1.2.0-hca488c2_0
  brotli-bin         conda-forge/osx-arm64::brotli-bin-1.2.0-hce9b42c_0
  brotli-python      conda-forge/osx-arm64::brotli-python-1.2.0-py311h69b7e7c_0
  c-ares             conda-forge/osx-arm64::c-ares-1.34.5-h5505292_0
  certifi            conda-forge/noarch::certifi-2025.11.12-pyhd8ed1ab_0
  cffi               conda-forge/osx-arm64::cffi-2.0.0-py311hd10dc20_1
  charset-normalizer conda-forge/noarch::charset-normalizer-3.4.4-pyhd8ed1ab_0
  click              conda-forge/noarch::click-8.3.1-pyh707e725_0
  click-plugins      conda-forge/noarch::click-plugins-1.1.1.2-pyhd8ed1ab_0
  cligj              conda-forge/noarch::cligj-0.7.2-pyhd8ed1ab_2
  contourpy          conda-forge/osx-arm64::contourpy-1.3.3-py311h5a5e7c7_3
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_1
  fiona              conda-forge/osx-arm64::fiona-1.10.1-py311h595b8b0_3
  folium             conda-forge/noarch::folium-0.20.0-pyhd8ed1ab_0
  fonttools          conda-forge/osx-arm64::fonttools-4.60.1-py311ha9b3269_0
  freetype           conda-forge/osx-arm64::freetype-2.14.1-hce30654_0
  freexl             conda-forge/osx-arm64::freexl-2.0.0-h3ab3353_2
  geopandas          conda-forge/noarch::geopandas-1.1.1-pyhd8ed1ab_1
  geopandas-base     conda-forge/noarch::geopandas-base-1.1.1-pyha770c72_1
  geos               conda-forge/osx-arm64::geos-3.14.1-h5afe852_0
  geotiff            conda-forge/osx-arm64::geotiff-1.7.4-hf862be1_4
  gflags             conda-forge/osx-arm64::gflags-2.2.2-hf9b8971_1005
  giflib             conda-forge/osx-arm64::giflib-5.2.2-h93a5062_0
  glog               conda-forge/osx-arm64::glog-0.7.1-heb240a5_0
  h2                 conda-forge/noarch::h2-4.3.0-pyhcf101f3_0
  hpack              conda-forge/noarch::hpack-4.1.0-pyhd8ed1ab_0
  hyperframe         conda-forge/noarch::hyperframe-6.1.0-pyhd8ed1ab_0
  idna               conda-forge/noarch::idna-3.11-pyhd8ed1ab_0
  jinja2             conda-forge/noarch::jinja2-3.1.6-pyhd8ed1ab_0
  joblib             conda-forge/noarch::joblib-1.5.2-pyhd8ed1ab_0
  json-c             conda-forge/osx-arm64::json-c-0.18-he4178ee_0
  kiwisolver         conda-forge/osx-arm64::kiwisolver-1.4.9-py311h26d6576_2
  krb5               conda-forge/osx-arm64::krb5-1.21.3-h237132a_0
  lcms2              conda-forge/osx-arm64::lcms2-2.17-h7eeda09_0
  lerc               conda-forge/osx-arm64::lerc-4.0.0-hd64df32_1
  libabseil          conda-forge/osx-arm64::libabseil-20250512.1-cxx17_hd41c47c_0
  libarchive         conda-forge/osx-arm64::libarchive-3.8.2-gpl_h46575ef_100
  libarrow           conda-forge/osx-arm64::libarrow-22.0.0-h4a3aeba_4_cpu
  libarrow-acero     conda-forge/osx-arm64::libarrow-acero-22.0.0-hc317990_4_cpu
  libarrow-compute   conda-forge/osx-arm64::libarrow-compute-22.0.0-h75845d1_4_cpu
  libarrow-dataset   conda-forge/osx-arm64::libarrow-dataset-22.0.0-hc317990_4_cpu
  libarrow-substrait conda-forge/osx-arm64::libarrow-substrait-22.0.0-h144af7f_4_cpu
  libblas            conda-forge/osx-arm64::libblas-3.11.0-2_h51639a9_openblas
  libbrotlicommon    conda-forge/osx-arm64::libbrotlicommon-1.2.0-h87ba0bc_0
  libbrotlidec       conda-forge/osx-arm64::libbrotlidec-1.2.0-h95a88de_0
  libbrotlienc       conda-forge/osx-arm64::libbrotlienc-1.2.0-hb1b9735_0
  libcblas           conda-forge/osx-arm64::libcblas-3.11.0-2_hb0561ab_openblas
  libcrc32c          conda-forge/osx-arm64::libcrc32c-1.1.2-hbdafb3b_0
  libcurl            conda-forge/osx-arm64::libcurl-8.17.0-hdece5d2_0
  libcxx             conda-forge/osx-arm64::libcxx-21.1.6-hf598326_0
  libdeflate         conda-forge/osx-arm64::libdeflate-1.25-hc11a715_0
  libedit            conda-forge/osx-arm64::libedit-3.1.20250104-pl5321hafb1f1b_0
  libev              conda-forge/osx-arm64::libev-4.33-h93a5062_2
  libevent           conda-forge/osx-arm64::libevent-2.1.12-h2757513_1
  libfreetype        conda-forge/osx-arm64::libfreetype-2.14.1-hce30654_0
  libfreetype6       conda-forge/osx-arm64::libfreetype6-2.14.1-h6da58f4_0
  libgdal-core       conda-forge/osx-arm64::libgdal-core-3.10.3-h2be85fc_26
  libgfortran        conda-forge/osx-arm64::libgfortran-15.2.0-hfcf01ff_1
  libgfortran5       conda-forge/osx-arm64::libgfortran5-15.2.0-h742603c_1
  libgoogle-cloud    conda-forge/osx-arm64::libgoogle-cloud-2.39.0-head0a95_0
  libgoogle-cloud-s~ conda-forge/osx-arm64::libgoogle-cloud-storage-2.39.0-hfa3a374_0
  libgrpc            conda-forge/osx-arm64::libgrpc-1.73.1-h3063b79_1
  libiconv           conda-forge/osx-arm64::libiconv-1.18-h23cfdf5_2
  libjpeg-turbo      conda-forge/osx-arm64::libjpeg-turbo-3.1.2-hc919400_0
  libkml             conda-forge/osx-arm64::libkml-1.3.0-hc33e383_1022
  liblapack          conda-forge/osx-arm64::liblapack-3.11.0-2_hd9741b5_openblas
  libnghttp2         conda-forge/osx-arm64::libnghttp2-1.67.0-hc438710_0
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.30-openmp_ha158390_3
  libopentelemetry-~ conda-forge/osx-arm64::libopentelemetry-cpp-1.21.0-he15edb5_1
  libopentelemetry-~ conda-forge/osx-arm64::libopentelemetry-cpp-headers-1.21.0-hce30654_1
  libparquet         conda-forge/osx-arm64::libparquet-22.0.0-h0ac143b_4_cpu
  libpng             conda-forge/osx-arm64::libpng-1.6.51-hfab5511_0
  libprotobuf        conda-forge/osx-arm64::libprotobuf-6.31.1-h658db43_2
  libre2-11          conda-forge/osx-arm64::libre2-11-2025.11.05-h91c62da_0
  librttopo          conda-forge/osx-arm64::librttopo-1.1.0-ha909e78_20
  libspatialindex    conda-forge/osx-arm64::libspatialindex-2.1.0-h57eeb1c_0
  libspatialite      conda-forge/osx-arm64::libspatialite-5.1.0-gpl_ha239c29_119
  libssh2            conda-forge/osx-arm64::libssh2-1.11.1-h1590b86_0
  libthrift          conda-forge/osx-arm64::libthrift-0.22.0-h14a376c_1
  libtiff            conda-forge/osx-arm64::libtiff-4.7.1-h4030677_1
  libutf8proc        conda-forge/osx-arm64::libutf8proc-2.11.1-hd2415e0_0
  libwebp-base       conda-forge/osx-arm64::libwebp-base-1.6.0-h07db88b_0
  libxcb             conda-forge/osx-arm64::libxcb-1.17.0-hdb1d25a_0
  libxml2            conda-forge/osx-arm64::libxml2-2.15.1-h9329255_0
  libxml2-16         conda-forge/osx-arm64::libxml2-16-2.15.1-h0ff4647_0
  libxml2-devel      conda-forge/osx-arm64::libxml2-devel-2.15.1-h9329255_0
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-21.1.6-h4a912ad_0
  lz4-c              conda-forge/osx-arm64::lz4-c-1.10.0-h286801f_1
  lzo                conda-forge/osx-arm64::lzo-2.10-h925e9cb_1002
  mapclassify        conda-forge/noarch::mapclassify-2.10.0-pyhd8ed1ab_1
  markupsafe         conda-forge/osx-arm64::markupsafe-3.0.3-py311ha9b3269_0
  matplotlib-base    conda-forge/osx-arm64::matplotlib-base-3.10.8-py311h29553df_0
  minizip            conda-forge/osx-arm64::minizip-4.0.10-hff1a8ea_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyhd8ed1ab_1
  networkx           conda-forge/noarch::networkx-3.6-pyhcf101f3_0
  nlohmann_json      conda-forge/osx-arm64::nlohmann_json-3.12.0-h248ca61_1
  numpy              conda-forge/osx-arm64::numpy-2.3.5-py311h8685306_0
  openjpeg           conda-forge/osx-arm64::openjpeg-2.5.4-hbfb3c88_0
  orc                conda-forge/osx-arm64::orc-2.2.1-h4fd0076_0
  packaging          conda-forge/noarch::packaging-25.0-pyh29332c3_1
  pandas             conda-forge/osx-arm64::pandas-2.3.3-py311hdb8e4fa_1
  pcre2              conda-forge/osx-arm64::pcre2-10.46-h7125dd6_0
  pillow             conda-forge/osx-arm64::pillow-12.0.0-py311h890502c_0
  proj               conda-forge/osx-arm64::proj-9.7.0-hf83150c_0
  prometheus-cpp     conda-forge/osx-arm64::prometheus-cpp-1.3.0-h0967b3e_0
  pthread-stubs      conda-forge/osx-arm64::pthread-stubs-0.4-hd74edd7_1002
  pyarrow            conda-forge/osx-arm64::pyarrow-22.0.0-py311ha1ab1f8_0
  pyarrow-core       conda-forge/osx-arm64::pyarrow-core-22.0.0-py311hf3e52b4_0_cpu
  pycparser          conda-forge/noarch::pycparser-2.22-pyh29332c3_1
  pyogrio            conda-forge/osx-arm64::pyogrio-0.11.0-py311h595b8b0_0
  pyparsing          conda-forge/noarch::pyparsing-3.2.5-pyhcf101f3_0
  pyproj             conda-forge/osx-arm64::pyproj-3.7.2-py311h55f0a08_2
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha55dd90_7
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0.post0-pyhe01879c_2
  python-tzdata      conda-forge/noarch::python-tzdata-2025.2-pyhd8ed1ab_0
  python_abi         conda-forge/noarch::python_abi-3.11-8_cp311
  pytz               conda-forge/noarch::pytz-2025.2-pyhd8ed1ab_0
  qhull              conda-forge/osx-arm64::qhull-2020.2-h420ef59_5
  re2                conda-forge/osx-arm64::re2-2025.11.05-h64b956e_0
  requests           conda-forge/noarch::requests-2.32.5-pyhd8ed1ab_0
  rtree              conda-forge/noarch::rtree-1.4.1-pyh11ca60a_0
  scikit-learn       conda-forge/osx-arm64::scikit-learn-1.7.2-py311h0f965f6_0
  scipy              conda-forge/osx-arm64::scipy-1.16.3-py311h2734c94_1
  shapely            conda-forge/osx-arm64::shapely-2.1.2-py311hd4fb369_2
  six                conda-forge/noarch::six-1.17.0-pyhe01879c_1
  snappy             conda-forge/osx-arm64::snappy-1.2.2-hada39a4_1
  sqlite             conda-forge/osx-arm64::sqlite-3.50.4-hb5dd463_0
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.6.0-pyhecae5ae_0
  unicodedata2       conda-forge/osx-arm64::unicodedata2-17.0.0-py311h9408147_1
  uriparser          conda-forge/osx-arm64::uriparser-0.9.8-h00cdb27_0
  urllib3            conda-forge/noarch::urllib3-2.5.0-pyhd8ed1ab_0
  xerces-c           conda-forge/osx-arm64::xerces-c-3.3.0-hd62221f_0
  xorg-libxau        conda-forge/osx-arm64::xorg-libxau-1.0.12-hc919400_1
  xorg-libxdmcp      conda-forge/osx-arm64::xorg-libxdmcp-1.1.5-hc919400_1
  xyzservices        conda-forge/noarch::xyzservices-2025.11.0-pyhd8ed1ab_0
  zlib               conda-forge/osx-arm64::zlib-1.3.1-h8359307_2
  zlib-ng            conda-forge/osx-arm64::zlib-ng-2.2.5-h3470cca_0
  zstandard          conda-forge/osx-arm64::zstandard-0.25.0-py311h5bb9006_1
  zstd               conda-forge/osx-arm64::zstd-1.5.7-h6491c7d_2

The following packages will be UPDATED:

  ca-certificates                      2025.10.5-hbd8a1cb_0 --> 2025.11.12-hbd8a1cb_0
  openssl                                  3.5.4-h5503f6c_0 --> 3.6.0-h5503f6c_0



Downloading and Extracting Packages:
pandas-2.3.3         | 13.7 MB   |                                       |   0%
scipy-1.16.3         | 13.4 MB   |                                       |   0%

libgdal-core-3.10.3  | 8.1 MB    |                                       |   0%


matplotlib-base-3.10 | 7.9 MB    |                                       |   0%



numpy-2.3.5          | 7.0 MB    |                                       |   0%




pyarrow-core-22.0.0  | 4.1 MB    |                                       |   0%





libarrow-22.0.0      | 4.0 MB    |                                       |   0%






aws-sdk-cpp-1.11.606 | 3.0 MB    |                                       |   0%







openssl-3.6.0        | 3.0 MB    |                                       |   0%








fonttools-4.60.1     | 2.8 MB    |                                       |   0%









proj-9.7.0           | 2.7 MB    |                                       |   0%










libspatialite-5.1.0  | 2.6 MB    |                                       |   0%











libarrow-compute-22. | 2.1 MB    |                                       |   0%












networkx-3.6         | 1.5 MB    |                                       |   0%













geos-3.14.1          | 1.5 MB    |                                       |   0%














xerces-c-3.3.0       | 1.2 MB    |                                       |   0%
















In [ ]:
# Imports & robust repo-root detection
from pathlib import Path
import zipfile
import pandas as pd
import numpy as np
import geopandas as gpd

def find_repo_root(start: Path | None = None) -> Path:
    p = (start or Path.cwd()).resolve()
    markers = ("data", ".git", "pyproject.toml", "Makefile")
    while p.parent != p and not any((p / m).exists() for m in markers):
        p = p.parent
    return p

REPO = find_repo_root()
DATA = REPO / "data"
RAW = DATA / "raw"
EXT = DATA / "external"
INTERIM = DATA / "interim"; INTERIM.mkdir(parents=True, exist_ok=True)
PROCESSED = DATA / "processed"; PROCESSED.mkdir(parents=True, exist_ok=True)

# Services 
SERV_RAW = RAW / "services"
YMCA_F   = SERV_RAW / "ymca_sd.csv"
LIBS_F   = SERV_RAW / "sd_public_libraries.csv"
LIBS2_F  = SERV_RAW / "Library.csv"                   
REC_F    = SERV_RAW / "rec_centers_datasd.csv"
REC2_F   = SERV_RAW / "Recreation_Centers_SD.csv"  
PARKS_F  = SERV_RAW / "Parks_SD.csv"
GTFS_STOPS_F  = SERV_RAW / "Transit_Stops_GTFS_20251028.csv"
GTFS_ROUTES_F = SERV_RAW / "Transit_Routes_GTFS.csv"

# TIGER 2023 shapefiles (California = 06)
TIGER_DIR = EXT / "tiger_tracts_2023"
TRACT_ZIP = TIGER_DIR / "tl_2023_06_tract.zip"    # tracts for CA
PLACE_ZIP = TIGER_DIR / "tl_2023_06_place.zip"    # cities/places
COUNTY_ZIP= TIGER_DIR / "tl_2023_us_county.zip"   # US counties

# ACS baseline 
ACS_CLEAN = PROCESSED / "acs_baselines_tract_2023_clean.csv"

print("Repo root:", REPO)
for p in [YMCA_F, LIBS_F, LIBS2_F, REC_F, REC2_F, PARKS_F, GTFS_STOPS_F, GTFS_ROUTES_F, TRACT_ZIP, ACS_CLEAN]:
    print(f"{p.relative_to(REPO)!s:<80} exists={p.exists()}")

False False False
Tracts file: None

In [ ]:
# Read tracts from the zipped shapefile directly (GeoPandas can read .zip via fiona)
tracts_ca = gpd.read_file(f"zip://{TRACT_ZIP}")
print(tracts_ca.crs)
tracts_ca = tracts_ca.to_crs(4326)

# Keep San Diego County only (STATEFP='06', COUNTYFP='073')
tracts_sd = tracts_ca.query("(STATEFP == '06') and (COUNTYFP == '073')").copy()

# Keep a compact set of ID columns for later joins
tracts_sd = tracts_sd[["STATEFP","COUNTYFP","TRACTCE","GEOID","NAME","NAMELSAD","ALAND","AWATER","geometry"]]
tracts_sd = tracts_sd.sort_values("GEOID").reset_index(drop=True)

print("San Diego tracts:", len(tracts_sd))
tracts_sd.head(2)

EPSG:4269
San Diego tracts: 737

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,ALAND,AWATER,geometry
0,06,073,000100,06073000100,1,Census Tract 1,1536251,0,"POLYGON ((-117.1949 32.75278, -117.19471 32.75..."
1,06,073,000201,06073000201,2.01,Census Tract 2.01,864211,0,"POLYGON ((-117.17887 32.75765, -117.17797 32.7..."

In [ ]:
# 2) Utilities for consistent point ingestion
def best_col(cols, candidates):
    for c in candidates:
        if c in cols:
            return c
    return None

def read_points_csv(path: Path, source_name: str) -> gpd.GeoDataFrame:
    df = pd.read_csv(path, dtype=str, low_memory=False)
    # Infer lat/lon
    lat_col = best_col(df.columns, ["lat","latitude","stop_lat","y","Lat","Latitude"])
    lon_col = best_col(df.columns, ["lng","lon","longitude","stop_lon","x","Long","Longitude"])
    if lat_col is None or lon_col is None:
        raise ValueError(f"{source_name}: could not find latitude/longitude columns in {list(df.columns)[:12]}...")

    # Coerce to numeric; drop invalid
    df["_lat"] = pd.to_numeric(df[lat_col], errors="coerce")
    df["_lon"] = pd.to_numeric(df[lon_col], errors="coerce")
    df = df.dropna(subset=["_lat","_lon"]).copy()

    gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["_lon"], df["_lat"], crs="EPSG:4326"))
    gdf["source"] = source_name
    return gdf

def read_optional_points(path: Path, source_name: str) -> gpd.GeoDataFrame | None:
    if path.exists():
        try:
            return read_points_csv(path, source_name)
        except Exception as e:
            print(f"[WARN] {source_name}: {e}")
            return None
    else:
        return None

In [5]:
def pick_latlon(cols):
    cols_l = {c.lower(): c for c in cols}
    pairs = [
        ("lat", "lon"),
        ("lat", "lng"),
        ("latitude", "longitude"),
        ("y", "x"),
        ("point_y", "point_x"),
        ("stop_lat", "stop_lon"),
    ]
    for a, b in pairs:
        if a in cols_l and b in cols_l:
            return cols_l[a], cols_l[b]
    return None, None

def read_optional_points(csv_path: Path, label: str):
    if not csv_path.exists():
        print(f"[WARN] {label}: file missing -> {csv_path}")
        return None
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"[WARN] {label}: could not read CSV ({e})")
        return None

    lat_col, lon_col = pick_latlon(df.columns)
    if lat_col is None or lon_col is None:
        print(f"[WARN] {label}: could not find latitude/longitude columns in {list(df.columns)}...")
        return None

    gdf = gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df[lon_col], df[lat_col]),
        crs="EPSG:4326",
    )

    # keep a small set of context columns when present
    keep_candidates = ["name", "org", "address", "city", "state", "zip", "website", "source"]
    keep = [c for c in keep_candidates if c in gdf.columns]
    return gdf[keep + ["geometry"]].copy()

In [ ]:
gdfs = []

# Libraries
libs = read_optional_points(LIBS2_F, "Libraries_SD_alt")
if libs is None:
    libs = read_optional_points(LIBS_F, "Libraries_SD")
if libs is not None:
    libs["category"] = "library"
    gdfs.append(libs)

# Recreation centers: try both in sequence
rec = read_optional_points(REC2_F, "Rec_Centers_alt")
if rec is None:
    rec = read_optional_points(REC_F, "Rec_Centers")
if rec is not None:
    rec["category"] = "rec_center"
    gdfs.append(rec)

# YMCA
ymca = read_optional_points(YMCA_F, "YMCA")
if ymca is not None:
    ymca["category"] = "ymca"
    gdfs.append(ymca)

# Parks 
parks = read_optional_points(PARKS_F, "Parks_SD")
if parks is not None:
    parks["category"] = "park"
    gdfs.append(parks)

# GTFS stops
gtfs = read_optional_points(GTFS_STOPS_F, "GTFS_Stops")
if gtfs is not None:
    gtfs["category"] = "transit_stop"
    gdfs.append(gtfs)

print("Layers loaded:", [g.shape for g in gdfs])
services_all = pd.concat(gdfs, ignore_index=True) if gdfs else gpd.GeoDataFrame(columns=["category", "geometry"], crs="EPSG:4326")
print("Total service points:", len(services_all))

[WARN] Libraries_SD_alt: could not find latitude/longitude columns in ['OID_', 'WEBSITE', 'ADDRESS', 'DISTRICT', 'NAME', 'TYPE', 'PHONE', 'ZIP', 'CITY', 'DATA_SRC', 'UPDATE_DATE']...
[WARN] Libraries_SD: could not find latitude/longitude columns in ['org', 'name', 'address', 'city', 'state', 'zip', 'phone', 'website', 'source']...
[WARN] YMCA: could not find latitude/longitude columns in ['org', 'name', 'address', 'city', 'state', 'zip', 'phone', 'fax', 'website', 'source']...
[WARN] Parks_SD: could not find latitude/longitude columns in ['objectid', 'common_name', 'desig_use', 'acres', 'address_lo', 'community', 'use_restriction', 'dedicated_park', 'full_name', 'undeveloped_ac', 'useable_ac', 'gross_ac', 'maint_entity', 'recycled_water', 'play_area_cnt', 'cd', 'dms', 'x_coord', 'y_coord', 'year_acquired', 'read_ac', 'notes', 'year_constructed', 'year_assessed', 'pci', 'service_district', 'playground', 'tot_lot', 'baseball_50_6', 'baseball_90', 'softball', 'multi_purpose', 'f_2_baselet', 'basketball', 'tennis', 'sand_vball', 'comfort_station', 'concession_stand', 'pickleball', 'field_lighting_cnt', 'field_lighting', 'created_user', 'created_date', 'last_edited_user', 'last_edited_date', 'globalid', 'crg', 'gdp_url', 'fitness_st', 'shape_Length', 'shape_Area']...
Layers loaded: [(61, 4), (6230, 2)]
Total service points: 6291

In [8]:
# Ensure same CRS
services_all = services_all.to_crs(4326)
tracts_sd = tracts_sd.to_crs(4326)

# Keep only points inside San Diego County tracts
points_in_sd = gpd.sjoin(services_all, tracts_sd[["GEOID","geometry"]], how="inner", predicate="within")
print("Points matched to SD tracts:", len(points_in_sd))

# Save a GeoJSON of the matched points (handy for quick map checks)
points_geojson = INTERIM / "services_points_in_sd_2023.geojson"
points_in_sd.to_file(points_geojson, driver="GeoJSON")
print("Wrote:", points_geojson)

Points matched to SD tracts: 6230
Wrote: /Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/data/interim/services_points_in_sd_2023.geojson

In [ ]:
# Count by tract & category
counts = (
    points_in_sd
      .groupby(["GEOID","category"], as_index=False)
      .size()
      .rename(columns={"size":"count"})
)

# Pivot to wide columns (ymca_ct, library_ct, rec_center_ct, park_ct, gtfs_stop_ct)
wide = counts.pivot(index="GEOID", columns="category", values="count").fillna(0).astype(int)
wide.columns = [f"{c}_ct" for c in wide.columns]
wide = wide.reset_index()

# Add a total services column excluding GTFS unless desired
service_cols = [c for c in wide.columns if c.endswith("_ct") and c != "gtfs_stop_ct"]
wide["services_ct"] = wide[service_cols].sum(axis=1)

wide.head()

         GEOID  transit_stop_ct  services_ct
0  06073000100                7            7
1  06073000201                7            7
2  06073000202               11           11
3  06073000301                7            7
4  06073000302               10           10

In [ ]:
# Load canonical tract-level baseline
acs = pd.read_csv(ACS_CLEAN, dtype={"GEOID":"string"})

# Merge
tract_services = tracts_sd[["GEOID"]].merge(wide, on="GEOID", how="left").fillna(0)
tract_services = tract_services.merge(
    acs[["GEOID","NAME","pop_total","youth_5_17","youth_10_19","youth_5_17_per_1k","youth_10_19_per_1k"]],
    on="GEOID",
    how="left"
)

# Per-1k youth (guard zeros)
def per_1k(n, denom):
    n = n.astype("float64")
    d = denom.astype("float64")
    out = np.where((d > 0) & np.isfinite(d), 1000.0 * n / d, np.nan)
    return out

# Compute per-1k for key categories against 5–17 and 10–19
for base_col in ["ymca_ct","library_ct","rec_center_ct","park_ct","services_ct"]:
    if base_col in tract_services.columns:
        tract_services[f"{base_col}_per_1k_5_17"]  = per_1k(tract_services[base_col], tract_services["youth_5_17"])
        tract_services[f"{base_col}_per_1k_10_19"] = per_1k(tract_services[base_col], tract_services["youth_10_19"])

# Include GTFS stop density per 10k population as an access proxy
if "gtfs_stop_ct" in tract_services.columns:
    tract_services["gtfs_stop_ct_per_10k_pop"] = per_1k(tract_services["gtfs_stop_ct"], tract_services["pop_total"]) * 10

# Order columns for readability
front = ["GEOID","NAME","pop_total","youth_5_17","youth_10_19","youth_5_17_per_1k","youth_10_19_per_1k"]
count_cols = [c for c in tract_services.columns if c.endswith("_ct")]
rate_cols  = [c for c in tract_services.columns if c.endswith("_per_1k_5_17") or c.endswith("_per_1k_10_19") or c.endswith("_per_10k_pop")]
other_cols = [c for c in tract_services.columns if c not in front+count_cols+rate_cols]
tract_services = tract_services[front + sorted(count_cols) + sorted(rate_cols) + sorted(other_cols)]

print("Rows:", len(tract_services))
tract_services.head(3)

Rows: 737

,GEOID,NAME,pop_total,youth_5_17,youth_10_19,youth_5_17_per_1k,youth_10_19_per_1k,services_ct,transit_stop_ct,services_ct_per_1k_10_19,services_ct_per_1k_5_17
0,06073000100,Census Tract 1; San Diego County; California,2746.0,360.0,310.0,131.099782,112.891479,7.0,7.0,22.580645,19.444444
1,06073000201,Census Tract 2.01; San Diego County; California,2376.0,355.0,279.0,149.410774,117.424242,7.0,7.0,25.089606,19.718310
2,06073000202,Census Tract 2.02; San Diego County; California,4019.0,344.0,247.0,85.593431,61.458074,11.0,11.0,44.534413,31.976744

In [ ]:
# CSV for modeling / dashboard plumbing
out_csv = PROCESSED / "services_by_tract_2023.csv"
tract_services.to_csv(out_csv, index=False)
print("Wrote:", out_csv)

# Write a GeoPackage with tract geometries + counts for quick mapping
tracts_counts = tracts_sd.merge(tract_services, on="GEOID", how="left")
out_gpkg = PROCESSED / "services_by_tract_2023.gpkg"
tracts_counts.to_file(out_gpkg, layer="tract_services", driver="GPKG")
print("Wrote:", out_gpkg)

# Quick summaries
display(tract_services.describe(include="number").T.head(12))
for col in ["ymca_ct","library_ct","rec_center_ct","park_ct","services_ct"]:
    if col in tract_services.columns:
        print(f"{col}: nonzero tracts = {(tract_services[col]>0).sum()} / {len(tract_services)}")

Wrote: /Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/data/processed/services_by_tract_2023.csv
Wrote: /Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/data/processed/services_by_tract_2023.gpkg

,count,mean,std,min,25%,50%,75%,max
pop_total,737.0,4454.249661,2107.362836,0.0,3313.000000,4257.000000,5436.000000,40481.000000
youth_5_17,737.0,687.552239,437.399949,0.0,422.000000,633.000000,897.000000,4064.000000
youth_10_19,737.0,553.706920,426.976540,0.0,316.000000,494.000000,703.000000,5984.000000
youth_5_17_per_1k,735.0,148.527286,60.066114,0.0,116.088617,155.036095,187.048111,338.547747
youth_10_19_per_1k,735.0,119.281729,59.520336,0.0,85.907905,117.724519,146.556075,688.869153
services_ct,737.0,8.453189,9.007593,0.0,3.000000,7.000000,11.000000,90.000000
transit_stop_ct,737.0,8.453189,9.007593,0.0,3.000000,7.000000,11.000000,90.000000
services_ct_per_1k_10_19,730.0,36.670004,129.648161,0.0,5.649718,13.640487,26.306185,2000.000000
services_ct_per_1k_5_17,728.0,27.798762,86.122625,0.0,4.379034,10.605329,21.178180,1444.444444

services_ct: nonzero tracts = 650 / 737